---
abstract: 'trade Bitcoin with the MtGox API'
author:
  - 'Michael Hendricks, C<< <michael@ndrix.org> >>'
  - 'Michael Hendricks <michael@ndrix.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-MtGox
no_index:
  directory:
    - inc
    - t
requires:
  Digest::SHA: 0
  JSON::Any: 1.25
  MIME::Base64: 0
  Time::HiRes: 0
  URI: 1.58
  WWW::Mechanize: 1.66
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.03
